### ISSUE TITLE
Tunneling traffic through proxy

### ISSUE THREAD

**Issue by nexon33** [eger-geger/FryProxy#11]
How can I tunnel traffic through the proxy when modifying the hosts file? I modified the hosts file and added `127.0.0.1 phpmyadmin.test` and now I want to make it so when I browse to phpmyadmin.test that the connection goes through the proxy instead of having to configure the proxy in the browser. Is there any way to do this?

**Comment by eger-geger** [comment]
Start the proxy on your localhost on default HTTP/S ports.
