### ISSUE TITLE
how create fry.pfx

### ISSUE THREAD

**Issue by gitlsl** [eger-geger/FryProxy#4]
i want to know how to create fry.pfx by my self , and whether  a    .cert file can be used replcae .pfx , can you help me! 3q

**Comment by eger-geger** [comment]
I've used _makecert_ and _pvk2pfx_ tools which are part if Visual Studio installation. They are meant to generate certificate for testing and development environments. Here is some nice [article|http://www.digitallycreated.net/Blog/38/using-makecert-to-create-certificates-for-development] on how  to use them to generate local self-signed certificate (which _fry.pfx_ actually is).

**Comment by gitlsl** [comment]
@eger-geger oh 3q and i got a new question
 many website   when we first open  is  http://www.aaa.com  then it jump https://www.aaa.com  
 so when i use fryfox, i need set  http port ， https port  to make it work fine, 
but in fiddler core (i think you must know it)  the default http port is 8888  ,  we only need set the proxy port to 8888 no matter the url starts with "http" or "https" ,  so is there any idea work it ?
sorry for my english
best wish for you

**Comment by eger-geger** [comment]
You could try to use SSL version for both types of requests but I did not test such scenario.
